# docker-compose.yml
version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - ollama1
      - ollama2
    networks: [ollama_network]

  ollama1:
    image: ollama/ollama:latest
    container_name: ollama1
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_NUM_PARALLEL=4      
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility 
    volumes:
      - ollama1:/root/.ollama
    networks: [ollama_network]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  ollama2:
    image: ollama/ollama:latest
    container_name: ollama2
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_NUM_PARALLEL=4
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ollama2:/root/.ollama
    networks: [ollama_network]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ollama1: {}
  ollama2: {}

networks:
  ollama_network: {}
